

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Prafful lachhwani
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
       
        initComponents();
        this.setLocationRelativeTo(null);
        database();
        setIcon();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        show_more = new javax.swing.JDialog();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        t7 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        c2 = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        t8 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        c3 = new javax.swing.JComboBox();
        c5 = new javax.swing.JComboBox();
        c4 = new javax.swing.JComboBox();
        jButton6 = new javax.swing.JButton();
        l21 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        about_us = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        contact_us = new javax.swing.JDialog();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        adminJPG = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tchrList = new javax.swing.JList();
        details = new javax.swing.JPanel();
        t1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        pwd3 = new javax.swing.JPasswordField();
        pwd2 = new javax.swing.JPasswordField();
        t2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();

        show_more.setMinimumSize(new java.awt.Dimension(620, 323));
        show_more.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                show_moreWindowClosing(evt);
            }
        });
        show_more.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(240, 240, 240));
        jLabel10.setText("Gender");
        show_more.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 107, -1));

        jLabel14.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(240, 240, 240));
        jLabel14.setText("Mobile No");
        show_more.getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 71, 107, -1));

        t7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        t7.setEnabled(false);
        show_more.getContentPane().add(t7, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 68, 150, -1));

        jLabel15.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(240, 240, 240));
        jLabel15.setText("Teacher type");
        show_more.getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));

        c2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        c2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PGT", "TGT", "PRT" }));
        c2.setEnabled(false);
        c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2ActionPerformed(evt);
            }
        });
        show_more.getContentPane().add(c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 131, -1));

        jLabel16.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(240, 240, 240));
        jLabel16.setText("Email ID");
        show_more.getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        t8.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        t8.setEnabled(false);
        show_more.getContentPane().add(t8, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 117, 280, -1));

        jLabel17.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(240, 240, 240));
        jLabel17.setText("DOB");
        show_more.getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 166, 107, -1));

        c3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        c3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        c3.setEnabled(false);
        c3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c3ActionPerformed(evt);
            }
        });
        show_more.getContentPane().add(c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, -1, -1));

        c5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        c5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2012", "2013", "2014" }));
        c5.setEnabled(false);
        c5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c5ActionPerformed(evt);
            }
        });
        show_more.getContentPane().add(c5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 90, -1));

        c4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        c4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        c4.setEnabled(false);
        c4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c4ActionPerformed(evt);
            }
        });
        show_more.getContentPane().add(c4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, -1, -1));

        jButton6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jButton6.setText("Save changes");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        show_more.getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 191, -1));

        l21.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        l21.setForeground(new java.awt.Color(240, 240, 240));
        show_more.getContentPane().add(l21, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 23, 120, 30));

        jButton7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jButton7.setText("cancel");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        show_more.getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, 110, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EDIT2.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        show_more.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, -1, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/368073-background.jpg"))); // NOI18N
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        show_more.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 320));

        about_us.setTitle("About us");
        about_us.setMaximumSize(new java.awt.Dimension(580, 272));
        about_us.setMinimumSize(new java.awt.Dimension(580, 272));
        about_us.setUndecorated(true);
        about_us.setPreferredSize(new java.awt.Dimension(580, 272));
        about_us.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Monotype Corsiva", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText(" 1.Prafful Lachhwani");
        jLabel5.setToolTipText("");
        about_us.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, -1, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Monotype Corsiva", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("<Html><u>Class 12th IP project</u></html>");
        jLabel6.setToolTipText("");
        about_us.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Monotype Corsiva", 1, 36)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("2.Harsh thakur");
        jLabel18.setToolTipText("");
        about_us.getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, -1, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Monotype Corsiva", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("<html><u>Created by-</u></html>");
        jLabel7.setToolTipText("");
        about_us.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jButton12.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jButton12.setText("OK");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        about_us.getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 191, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/about_us bg.jpg"))); // NOI18N
        about_us.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 270));

        contact_us.setMaximumSize(new java.awt.Dimension(720, 278));
        contact_us.setMinimumSize(new java.awt.Dimension(720, 278));
        contact_us.setUndecorated(true);
        contact_us.setPreferredSize(new java.awt.Dimension(720, 278));
        contact_us.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/facebook-icon.png"))); // NOI18N
        jLabel19.setText("<html>find us on <br>facebook.com</html>");
        contact_us.getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, -1, -1));

        jLabel20.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("<html>Call us<br>+91 8962758754</html>");
        contact_us.getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));

        jLabel21.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/call2.png"))); // NOI18N
        contact_us.getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, 140));

        jLabel22.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("<html>Mail us at - <br>prafful.lachhwani@gmail.com<br>lachhwani.prafful@yahoo.com<br>harsh.thakur@gmail.com</html>");
        contact_us.getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jButton14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton14.setText("X");
        jButton14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton14MouseClicked(evt);
            }
        });
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        contact_us.getContentPane().add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, 40, 30));

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/contact-us-banner-1-860x280.jpg"))); // NOI18N
        contact_us.getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 280));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        adminJPG.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        adminJPG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin-banner_1.jpg"))); // NOI18N
        getContentPane().add(adminJPG, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 520, -1));

        exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/close.png"))); // NOI18N
        exit.setToolTipText("   Exit   ");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, 100, 100));

        TcherNme.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        TcherNme.setForeground(new java.awt.Color(240, 240, 240));
        getContentPane().add(TcherNme, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 550, 50));

        tchrList.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Teachers", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Monotype Corsiva", 1, 24), new java.awt.Color(0, 0, 0))); // NOI18N
        tchrList.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tchrList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tchrList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tchrListMouseClicked(evt);
            }
        });
        tchrList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                tchrListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(tchrList);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 320, 480));

        details.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Teacher Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Monotype Corsiva", 1, 20), new java.awt.Color(240, 240, 240))); // NOI18N
        details.setOpaque(false);
        details.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        t1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        t1.setFocusable(false);
        details.add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 160, -1));

        jLabel8.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("Governes Class");
        details.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 190, 30));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Change Password", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Monotype Corsiva", 1, 18), new java.awt.Color(240, 240, 240))); // NOI18N
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(240, 240, 240));
        jLabel12.setText("Confirm Password");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 160, 30));

        jLabel13.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(240, 240, 240));
        jLabel13.setText("New Password");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 150, 30));

        jButton3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jButton3.setText("Change");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, -1, -1));

        pwd3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jPanel1.add(pwd3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 180, -1));

        pwd2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jPanel1.add(pwd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 180, -1));

        details.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 390, 160));

        t2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        t2.setFocusable(false);
        details.add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 160, -1));

        jLabel9.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setText("Status");
        details.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 110, 30));

        t3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        t3.setFocusable(false);
        details.add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 160, -1));

        jLabel11.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(240, 240, 240));
        jLabel11.setText("No of question Entered");
        details.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 270, 30));

        jButton4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jButton4.setText("See more");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        details.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, -1, -1));

        jButton5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jButton5.setText("Delete Account");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        details.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, -1));

        getContentPane().add(details, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, 490, 390));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminBag.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(989, 706));
        jLabel1.setMinimumSize(new java.awt.Dimension(989, 706));
        jLabel1.setPreferredSize(new java.awt.Dimension(989, 706));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 700));

        jMenu1.setText("Options");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("LogOut");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("About us");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        jMenuItem5.setText("About us");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Contact us");
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });

        jMenuItem9.setText("Contact us");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem9);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
      DefaultListModel dd=new  DefaultListModel();

    void database() {
     
        try{
    Class.forName("java.sql.Driver");
Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/teacher","root","123");
String sql="select distinct first_name,last_name from teacher_details";
Statement stmt=con.createStatement();
ResultSet rs=stmt.executeQuery(sql);
while(rs.next())
{
 String a=rs.getString("first_name");
 String b=rs.getString("last_name");

     dd.addElement(a+" "+b);
     tchrList.setModel(dd);
}

    }
    catch(Exception ex)
{
    JOptionPane.showMessageDialog(rootPane, ex.getMessage());
}  
 }
    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:
        int close = JOptionPane.showConfirmDialog(null,"are you sure?");
        if(close==0)
        System.exit(0);
     
    }//GEN-LAST:event_exitMouseClicked

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
        String user=System.getProperty("user.home");
        // TODO add your handling code here:
        ImageIcon image = new ImageIcon(user+"\\Desktop\\question bank\\src\\close2.png");
exit.setIcon(image);
    }//GEN-LAST:event_exitMouseEntered

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
        String user=System.getProperty("user.home");
        // TODO add your handling code here:
        ImageIcon image = new ImageIcon(user+"\\Desktop\\question bank\\src\\close.png");
exit.setIcon(image);     // TODO add your handling code here:
    }//GEN-LAST:event_exitMouseExited

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        //        this.setVisible(false);
        this.dispose();
        Login nn= new Login();
        nn.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void tchrListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tchrListMouseClicked
      
  
    }//GEN-LAST:event_tchrListMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       String name=(String) tchrList.getSelectedValue();
    
        String pwd21=new String(pwd2.getPassword());
String pwd31=new String(pwd3.getPassword());
if(pwd21.equals(pwd31)){
      try{
    Class.forName("java.sql.Driver");
Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/teacher","root","123");
String sql="update teacher_details set password='"+pwd21+"' where concat(concat(first_name,' '),last_name)='"+name+"'";
Statement stmt=con.createStatement();
stmt.executeUpdate(sql);
JOptionPane.showMessageDialog(rootPane,"Password changed");
    }
    catch(Exception ex)
{
    JOptionPane.showMessageDialog(rootPane, ex.getMessage());
}  
}
else{
JOptionPane.showMessageDialog(rootPane,"Password did not matched");
pwd2.setText("");
pwd3.setText("");
}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
show_more.setVisible(true);
show_more.setLocationRelativeTo(null);
String name=(String) tchrList.getSelectedValue();

try{
    Class.forName("java.sql.Driver");
Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/teacher","root","123");
String sql1="select sex,teacher_type,mobile_no,email_id,dob from teacher_details where concat(concat(first_name,' '),last_name)='"+name+"'";
System.out.println(sql1);
Statement stmt=con.createStatement();
ResultSet rs=stmt.executeQuery(sql1);
while(rs.next())
{
 String sex=rs.getString("sex");
  String Teacher_type=rs.getString("Teacher_type");
   String Mobile_no=rs.getString("mobile_no");
    String dob=rs.getString("dob");
     String email_id=rs.getString("email_id");

     
String date1=dob.substring(0,2);
String month=dob.substring(3,5);
String year=dob.substring(6,10);
     l21.setText(""+sex);

c2.setSelectedItem(Teacher_type);
c3.setSelectedItem(date1);
c5.setSelectedItem(year);
c4.setSelectedItem(month);
t7.setText(""+Mobile_no);
t8.setText(email_id);
}
}
    catch(Exception e)
{
    JOptionPane.showMessageDialog(rootPane, e.getMessage());
}   
      
  show_more.setVisible(true);
show_more.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        DefaultListModel dd1=new  DefaultListModel();
        String name=(String) tchrList.getSelectedValue();
           String name1=name.replace(" ","_");
        try{
    Class.forName("java.sql.Driver");
Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/teacher","root","123");
String sql1="Delete from teacher_details Where concat(concat(first_name,' '),last_name)='"+name+"'";
String sql2="Drop table "+name1+"";
            System.out.println(sql2);
Statement stmt=con.createStatement();
Statement stmt1=con.createStatement();
stmt.executeUpdate(sql1);
stmt1.execute(sql2);
JOptionPane.showMessageDialog(null, "Deleted");
this.setVisible(false);
       Admin nn1=new Admin();
       nn1.setVisible(true);
       TcherNme.setText("");
dd1.removeElement(name);
}
    catch(Exception e)
{
    System.out.println(e.getMessage());
}  
 
    }//GEN-LAST:event_jButton5ActionPerformed

    private void tchrListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_tchrListValueChanged
          String name=(String) tchrList.getSelectedValue();
           String name1=name.replace(" ","_");
                TcherNme.setText((String) tchrList.getSelectedValue());
         try{
    Class.forName("java.sql.Driver");
Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/teacher","root","123");
String sql="select distinct class from "+name1+"";
String teacher_name = (String) tchrList.getSelectedValue();
String sql1="select teacher_type from teacher_details where concat(concat(first_name,' '),last_name)='"+teacher_name+"'";
String sql2="select count(questions) as 'no' from "+name1+"";
Statement stmt=con.createStatement();
Statement stmt1=con.createStatement();
Statement stm2t=con.createStatement();
ResultSet rs=stmt.executeQuery(sql);
ResultSet rs1=stmt1.executeQuery(sql1);
ResultSet rs2=stm2t.executeQuery(sql2);
String b="";
while(rs.next())
{
 String a=rs.getString("class");

 b=b+a+",";
}t1.setText(b);
while(rs1.next())
{
 String ab=rs1.getString("teacher_type");
t2.setText(ab);
}

while(rs2.next())
{
int a=rs2.getInt("no");

t3.setText(""+a);
}
    }
    catch(Exception ex)
{
    JOptionPane.showMessageDialog(rootPane, ex.getMessage());
}   
      
      
    }//GEN-LAST:event_tchrListValueChanged

    private void c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c2ActionPerformed

    private void c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c3ActionPerformed

    private void c5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c5ActionPerformed

    private void c4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       String  name_edit=(String) tchrList.getSelectedValue();
        String  dob=c3.getSelectedItem()+"/"+c4.getSelectedItem()+"/"+c5.getSelectedItem();

        try{
            Class.forName("java.sql.Driver");
            Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/teacher","root","123");
            String sql="update teacher_details set teacher_type ='"+c2.getSelectedItem()+"' where concat(concat(first_name,' '),last_name)='"+name_edit+"'";
            String sql1="update teacher_details set mobile_no ='"+t7.getText()+"' where concat(concat(first_name,' '),last_name)='"+name_edit+"'";
            String sql2="update teacher_details set email_id ='"+t8.getText()+"' where concat(concat(first_name,' '),last_name)='"+name_edit+"'";
            String sql3="update teacher_details set dob ='"+dob+"' where concat(concat(first_name,' '),last_name)='"+name_edit+"'";

            System.out.println(sql);
            Statement stmt=con.createStatement();
            Statement stmt1=con.createStatement();
            Statement stmt2=con.createStatement();
            Statement stmt3=con.createStatement();
            stmt.executeUpdate(sql);
            stmt1.executeUpdate(sql1);
            stmt2.executeUpdate(sql2);
            stmt3.executeUpdate(sql3);
            show_more.setVisible(false);
            JOptionPane.showMessageDialog(rootPane,"Saved changes");
            c2.setEnabled(false);
            c3.setEnabled(false);
            c4.setEnabled(false);
            c5.setEnabled(false);
            t8.setEnabled(false);
            t7.setEnabled(false);
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        show_more.setVisible(false);
        c2.setEnabled(false);
        c3.setEnabled(false);
        c4.setEnabled(false);
        c5.setEnabled(false);
        t8.setEnabled(false);
        t7.setEnabled(false);
        c2.setSelectedIndex(0);
        c3.setSelectedIndex(0);
        c4.setSelectedIndex(0);
        c5.setSelectedIndex(0);
        t8.setText("");
        t7.setText("");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked

        c2.setEnabled(true);
        c3.setEnabled(true);
        c4.setEnabled(true);
        c5.setEnabled(true);
        t8.setEnabled(true);
        t7.setEnabled(true);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void show_moreWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_show_moreWindowClosing
        c2.setEnabled(false);
        c3.setEnabled(false);
        c4.setEnabled(false);
        c5.setEnabled(false);
        t8.setEnabled(false);
        t7.setEnabled(false);
    }//GEN-LAST:event_show_moreWindowClosing

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        about_us.setVisible(true);
        about_us.setLocationRelativeTo(null);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed

    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        contact_us.setVisible(true);
        contact_us.setLocationRelativeTo(null);

    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu4ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        about_us.setVisible(false);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton14MouseClicked
        // TODO add your handling code here:
        contact_us.setVisible(false);
    }//GEN-LAST:event_jButton14MouseClicked

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static final javax.swing.JLabel TcherNme = new javax.swing.JLabel();
    private javax.swing.JDialog about_us;
    private javax.swing.JLabel adminJPG;
    private javax.swing.JComboBox c2;
    private javax.swing.JComboBox c3;
    private javax.swing.JComboBox c4;
    private javax.swing.JComboBox c5;
    private javax.swing.JDialog contact_us;
    private javax.swing.JPanel details;
    private javax.swing.JLabel exit;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel l21;
    private javax.swing.JPasswordField pwd2;
    private javax.swing.JPasswordField pwd3;
    private javax.swing.JDialog show_more;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t7;
    private javax.swing.JTextField t8;
    private javax.swing.JList tchrList;
    // End of variables declaration//GEN-END:variables
    private void setIcon() {
      setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("question bank icon.png")));
    }
}
